### PR TITLE
unrefing the things if i can

### PR DESCRIPTION
**Pull request by soldair**

### CODE REVIEW

**Comment by soldair** [comment]
i know i probably dont need to check that timer has unref anymore...

**Comment by soldair** [comment]
this fixes  numbat-emitter holding the process open while testing

**Comment by mmalecki** [comment]
> i know i probably dont need to check that timer has unref anymore...
I think that's also true for the network socket - those got added in versions which I'd be embarrassed to run at this point ;). Unless lack of that check is causing problems, I'd say remove it and just call `unref()`.

Other than that nitpick, great idea and LGTM!

**Comment by soldair** [comment]
im not sure if all of the drivers expose unref on their connection objects so ill leave the check there
but remove it from timer

**Pull request merged**
